#!/bin/bash
# Setup AWS MCP Bridge after deployment

set -e

echo "🌉 Setting up AWS MCP Bridge..."

# Check if we're in the right directory
if [ ! -f "aws-infrastructure/main.tf" ]; then
    echo "❌ Please run this script from the semantic_mcp directory"
    exit 1
fi

# Check if Terraform has been applied
if [ ! -f "aws-infrastructure/terraform.tfstate" ]; then
    echo "❌ Terraform state not found. Please deploy AWS infrastructure first:"
    echo "   cd aws-infrastructure && ./deploy.sh"
    exit 1
fi

# Get API URL from Terraform output
cd aws-infrastructure
API_URL=$(terraform output -raw api_gateway_url 2>/dev/null)
cd ..

if [ -z "$API_URL" ]; then
    echo "❌ Could not get API Gateway URL from Terraform output"
    echo "Please check your deployment and try again"
    exit 1
fi

echo "✅ Found API URL: $API_URL"

# Update the bridge script with the real API URL
sed -i.bak "s|PLACEHOLDER_API_URL|$API_URL|g" aws-mcp-bridge.py

echo "✅ Bridge configured with API URL"

# Create a convenient wrapper script
cat > aws-mcp-bridge-configured.py << EOF
#!/usr/bin/env python3
"""
AWS MCP Bridge - Pre-configured for your deployment
Auto-generated by setup-aws-bridge.sh
"""

import os
import sys

# Set the API URL for this deployment
os.environ['AWS_MCP_API_URL'] = '$API_URL'

# Import and run the bridge
sys.path.insert(0, '$(pwd)')
from aws_mcp_bridge import main

if __name__ == "__main__":
    main()
EOF

chmod +x aws-mcp-bridge-configured.py

echo "✅ Created pre-configured bridge: aws-mcp-bridge-configured.py"

# Test the bridge
echo "🧪 Testing bridge connection..."
echo '{"jsonrpc": "2.0", "method": "initialize", "params": {"protocolVersion": "2024-11-05", "capabilities": {}, "clientInfo": {"name": "test", "version": "1.0.0"}}, "id": 1}' | python3 aws-mcp-bridge-configured.py | head -1

if [ $? -eq 0 ]; then
    echo "✅ Bridge test successful!"
else
    echo "❌ Bridge test failed. Check your AWS deployment."
    exit 1
fi

echo ""
echo "🎉 AWS MCP Bridge setup complete!"
echo ""
echo "📋 LangFlow Configuration:"
echo "   Mode: STDIO"
echo "   Command: /usr/bin/python3 $(pwd)/aws-mcp-bridge-configured.py"
echo "   Name: aws-semantic-mcp"
echo ""
echo "🔍 Debug mode (optional):"
echo "   Set environment variable: DEBUG=1"
echo "   Command: DEBUG=1 /usr/bin/python3 $(pwd)/aws-mcp-bridge-configured.py"
echo ""
echo "✨ Your local LangFlow can now connect to AWS cloud backend!"